### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by denys-panchuk** [denys-panchuk/homepage#3]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by 85coba** [comment]
<h2>Resume</h2>
                    <p></p>
                    <p>
                      I am a web developer. I've got some experience in MySQL,
                      PHP, HTML, JavaScript. I've been working with frameworks
                      such as Laravel, VueJs and little bit with Flutter for
                      mobile developing.
                    </p>
                    <p>
                      I haven't got many years of experience in developing. But
                      I'm a quick learner, responsible and have an ability and
                      desire to work hard on big and intresting projects.
                    </p>

**Comment by denys-panchuk** [comment]
You are the best. Tnx.
