### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by denys-panchuk** [denys-panchuk/homepage#4]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by 85coba** [comment]
<h1 class="name">Denys Panchuk</h1>
                    <div class="job">Freelancer</div>
                    <ul class="contacts">
                      <li>
                        <a
                          href="mailto:uapanchude@gmail.com"
                          rel="author"
                          class="mail"
                        >
                          <span>uapanchude@gmail.com</span>
                        </a>
                      </li>
                      <li>
                        Linkedin: https://www.linkedin.com/in/denys-panchuk/
                      </li>
                    </ul>
