### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by denys-panchuk** [denys-panchuk/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by 85coba** [comment]
<h3>EXPERIENCE</h3>
                <ul class="timeline">
                  <li>
                    <p><small>2004</small></p>
                    <p>
                      Began my career as a co-founder of a little computer game
                      club.
                    </p>
                  </li>

                  <li>
                    <p><small>2005</small></p>
                    <p>
                      Worked in Nestle Ukraine as SAP WM Administrator.
                      Responsibility: Providing support SAP LE-WM on
                      Distribution Center, Monitoring of SAP standard jobs,
                      Execute system health check, Conducting regular WH
                      inventories;
                    </p>
                  </li>
                  <li>
                    <p><small>2012</small></p>
                    <p>
                      Founded a company of selling car parts. It was a small
                      business, just four employees.
                    </p>
                  </li>

                  <li>
                    <p><small>2017</small></p>
                    <p>
                      Worked in building company Shynaka Ukraine as the chief of
                      a large department, this one include wood factory,
                      warehouse, transport and logistic, sales department. Also
                      was responsible for all IT issues in the company.
                    </p>
                  </li>
                  <li>
                    <p><small>2019</small></p>
                    <p>
                      Began working on freelance exchange Upwork.com as
                      freelancer web-developer.
                    </p>
                  </li>
                  <li>
                    <p><small>2020</small></p>
                    <p>Worked on firmply.com project as junior developer.</p>
                  </li>
                </ul>

**Comment by 85coba** [comment]
<h3>Education</h3>
                <ul class="timeline">
                  <li>
                    <p><small>2003</small></p>
                    <p>
                      Enrolled in the Lesya Ukrainka Eastern European National University of mathematical faculty.
                    </p>
                  </li>
                </ul>

**Comment by denys-panchuk** [comment]
Briliant!
