### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by denys-panchuk** [denys-panchuk/homepage#6]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by 85coba** [comment]
<section>
                  <h3>Languages</h3>
                  <p class="tags small">
                    <a
                      href="/uk-ua"
                      hreflang="uk"
                      rel="alternate"
                      class="language"
                      lang="uk"
                      >&#x1f1fa;&#x1f1e6; <span>УКРАЇНСЬКА</span></a
                    >
                    <a
                      href="/ru-ru"
                      hreflang="ru"
                      rel="alternate"
                      class="language"
                      lang="ru"
                      >&#x1f1f7;&#x1f1fa; <span>РУССКИЙ</span></a
                    >
                    <span class="language" lang="en"
                      >&#x1f1fa;&#x1f1f8; ENGLISH</span
                    >
                  </p>
                </section>
                <section>
                  <h3>
                    SKILLS
                  </h3>
                  <p class="tags small">
                    HTML, Object Oriented PHP, Laravel, JavaScript, Vue.js,
                    Vuex, MySQL, Restful API.
                  </p>
                </section>
                <section>
                  <h3>
                    PERSONAL QUALITIES
                  </h3>
                  <p class="tags small">
                    Responsibility, Learnability, Purposefulness, Stress
                    resistance.
                  </p>
                </section>
                <section>
                  <h3>
                    SPECIAL WISHES
                  </h3>
                  <p class="tags small">
                    Do not work at night on weekends)
                  </p>
                </section>

**Comment by denys-panchuk** [comment]
Awesome!!
